name: build atrifacts
on:
  release:
    types: [published]
jobs:
  publish_artifacts:
    name: publish artifacts
    runs-on: macos-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Install go tools
        run: go build main.go
      - name: compress
        run: tar -czvf main.tar.gz main
      - name: upload artifacts to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            main.tar.gz
            main


